build_image:
  tags:
  - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo $DOCKER_AUTH > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --destination $CI_REGISTRY/nielsole/kudos/kudos:latest --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile
